name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  DeployToDevelop:
    name: Deploy 
    runs-on: ubuntu-latest
    environment: TestEnvironment
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Deploy to develop
      run: dotnet publish --configuration Release --output /home/runner/work/
    - name: Deploy to staging
      run: dotnet publish --configuration Release --output /home/runner/work/
    - name: Deploy to production
      run: dotnet publish --configuration Release --output /home/runner/work/

  DeployToStaging:
    name: Deploy 
    runs-on: ubuntu-latest
    environment: TestEnvironment
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Deploy to staging
      run: dotnet publish --configuration Release --output /home/runner/work/
    - name: Deploy to production
      run: dotnet publish --configuration Release --output /home/runner/work/
